language: ruby

sudo: false

rvm:
  - 2.3.5
  - 2.4.2

services:
  - postgresql

before_script:
  - psql -c 'create database weather-station-test;' -U postgres

test:
  adapter: postgresql
  database: weather-station-test

script:
  - bundle exec rake
